# Generated by Django 5.2 on 2025-05-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='roles/', verbose_name='Лого'),
        ),
    ]
