# Generated by Django 5.2 on 2025-08-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antipatterns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antipatternexamplestoryacceptor',
            name='comment',
            field=models.CharField(blank=True, help_text='Как заметить причину поломки Акцептора?', max_length=200, verbose_name='Как заметить?'),
        ),
    ]
